### ISSUE TITLE
vue2 nuxt codeblock 粘贴 markdown 然后自动转换后异常 

### ISSUE THREAD

**Issue by know-that** [yanmao-cc/am-editor-nuxt#1]
![image](https://user-images.githubusercontent.com/31246220/170209072-241d6850-bde5-4925-aaa8-84408a5a122f.png)
![image](https://user-images.githubusercontent.com/31246220/170209129-4d7d9b91-e214-4016-bc32-64614bc75c91.png)
![image](https://user-images.githubusercontent.com/31246220/170209159-dace3f7d-281a-4f13-81a6-432a37ad7ff2.png)

markdown 内容

````bash
# install dependencies
$ npm install

# serve with hot reload at localhost:3000
$ npm run dev

# build for production and launch server
$ npm run build
$ npm run start

# generate static project
$ npm run generate
````

显示：
![image](https://user-images.githubusercontent.com/31246220/170209416-a3595b47-8257-4a55-aa32-a00637f919e0.png)

**Comment by big-camel** [comment]
编辑器和插件都是什么版本的？

**Comment by know-that** [comment]
> 编辑器和插件都是什么版本的？

![image](https://user-images.githubusercontent.com/31246220/170212940-0b550ab1-1003-41d2-826d-34e8a2e265f7.png)

**Comment by big-camel** [comment]
https://github.com/yanmao-cc/am-editor-nuxt/commit/29cc920c58e81d10950209fdea0ba29e9d06eef8
