### ISSUE TITLE
vue2 nuxt codeblock 写入 markdown文本 后回车不触发解析，并且预览模式也不解析

### ISSUE THREAD

**Issue by know-that** [yanmao-cc/am-editor-nuxt#2]
![image](https://user-images.githubusercontent.com/31246220/170395016-5c4daabe-35af-43b6-af2a-f856ef9dac86.png)

![image](https://user-images.githubusercontent.com/31246220/170394955-4b1e5c2a-e7d8-478e-ae31-bbd348e0ff95.png)

![image](https://user-images.githubusercontent.com/31246220/170394886-e836aaf0-f68e-4eba-b31a-48cfcff2cd8f.png)

**Comment by big-camel** [comment]
预览模式本身不解析markdown的

**Comment by big-camel** [comment]
所有的版本都更到 2.9.5 吧

**Comment by know-that** [comment]
> 预览模式本身不解析markdown的

后面会支持吗

**Comment by big-camel** [comment]
不会支持，本身编辑器就不获取markdown，为啥要直接markdown预览，这个需求可以找别的库

**Comment by know-that** [comment]
> 不会支持，本身编辑器就不获取markdown，为啥要直接markdown预览，这个需求可以找别的库
