### ISSUE TITLE
麻烦看看什么原因

### ISSUE THREAD

**Issue by know-that** [yanmao-cc/am-editor-nuxt#3]
![image](https://user-images.githubusercontent.com/31246220/185304576-57201066-783f-45cb-a75d-833143797a68.png)
![image](https://user-images.githubusercontent.com/31246220/185304603-9b6ab4c3-936e-45f0-9959-bbce993bbbb6.png)

报错了，卡片点击也报错，除了 代码块

**Comment by know-that** [comment]
另外 @aomao/plugin-lightblock 这个安装报错
![image](https://user-images.githubusercontent.com/31246220/185304970-81705cb7-6e2d-4141-8a04-7269398a0383.png)

**Comment by big-camel** [comment]
看不出来，有没有复现方式

**Comment by know-that** [comment]
> 看不出来，有没有复现方式

我是按照demo然后添加了官网的插件

```javascript
<template>
  <div>
    <am-toolbar v-if="engine" :engine="engine" :items="items" />
    <div ref="container" style="min-height: 500px"></div>
  </div>
</template>

<script>
let Component = {
  data: function () {
    return {
      engine: null,
      items: []
    };
  },
}
if (!process.client) {
} else {
  console.log(process)
  const Engine = require('@aomao/engine').default
  const Heading = require('@aomao/plugin-heading').default
  const AmToolbar = require('am-editor-toolbar-vue2')
  const { ToolbarPlugin, ToolbarComponent } = AmToolbar
  const CodeBlock = require('am-editor-codeblock-vue2')
  const { CodeBlockComponent } = CodeBlock
  const Bold = require('@aomao/plugin-bold').default
  const Alignment = require('@aomao/plugin-alignment').default
  const BackColor = require('@aomao/plugin-backcolor').default
  const Code = require('@aomao/plugin-code').default
  const File = require('@aomao/plugin-file').default
  const FontColor = require('@aomao/plugin-fontcolor').default
  const FontSize = require('@aomao/plugin-fontsize').default
  const FontFamily = require('@aomao/plugin-fontfamily').default
  const Hr = require('@aomao/plugin-hr').default
  const Indent = require('@aomao/plugin-indent').default
  const Italic = require('@aomao/plugin-italic').default
  const Image = require('@aomao/plugin-image')
  const { ImageComponent } = Image
  const Link = require('@aomao/plugin-link').default
  const LineHeight = require('@aomao/plugin-line-height').default
  // const LightBlock = require('@aomao/plugin-lightblock') // 插件无法安装
  const Mark = require('@aomao/plugin-mark').default
  const MarkRange = require('@aomao/plugin-mark-range').default
  const Math = require('@aomao/plugin-math').default
  const Mention = require('@aomao/plugin-mention').default
  const OrderedList = require('@aomao/plugin-orderedlist').default
  const PaintFormat = require('@aomao/plugin-paintformat').default
  const Quote = require('@aomao/plugin-quote').default
  const Redo = require('@aomao/plugin-redo').default
  const RemoveFormat = require('@aomao/plugin-removeformat').default
  const SelectAll = require('@aomao/plugin-selectall').default
  const StrikeThrough = require('@aomao/plugin-strikethrough').default
  const Status = require('@aomao/plugin-status').default
  const Sub = require('@aomao/plugin-sub').default
  const Sup = require('@aomao/plugin-sup').default
  const Table = require('@aomao/plugin-table')
  const { TableComponent } = Table
  const TaskList = require('@aomao/plugin-tasklist').default
  const Underline = require('@aomao/plugin-underline').default
  const Undo = require('@aomao/plugin-undo').default
  const UnorderedList = require('@aomao/plugin-unorderedlist').default
  const Video = require('@aomao/plugin-video').default

  Component = {
    name: "HelloWorld",
    components: {
      AmToolbar: AmToolbar.default,
    },
    data: function () {
      return {
        engine: null,
        items: [['collapse'],['heading','bold']]
      };
    },
    props: {
      msg: String,
    },
    mounted() {
      this.engine = new Engine(
        this.$refs.container,
        {
          config:{
            "heading":{
              //修改快捷键
              hotkey:{
                h1:"快捷键"
              }
            }
          },
          cards: [
            ToolbarComponent,
            CodeBlockComponent,
            ImageComponent,
            TableComponent
          ],
          plugins: [
            Heading,
            ToolbarPlugin,
            CodeBlock.default,
            Bold,
            Alignment,
            BackColor,
            Code,
            File,
            FontColor,
            FontSize,
            FontFamily,
            Hr,
            Indent,
            Italic,
            Image.default,
            Link,
            LineHeight,
            Mark,
            MarkRange,
            Math,
            Mention,
            OrderedList,
            PaintFormat,
            Quote,
            Redo,
            RemoveFormat,
            SelectAll,
            StrikeThrough,
            Status,
            Sub,
            Sup,
            Table.default,
            TaskList,
            Underline,
            Undo,
            UnorderedList,
            Video
          ]
        },
      );
    }
  };
}
export default Component
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
h3 {
  margin: 40px 0 0;
}
ul {
  list-style-type: none;
  padding: 0;
}
li {
  display: inline-block;
  margin: 0 10px;
}
a {
  color: #42b983;
}
</style>

```

**Comment by know-that** [comment]
> > 看不出来，有没有复现方式
> 
> 我是按照demo然后添加了官网的插件
> 
> ```js
> <template>
>   <div>
>     <am-toolbar v-if="engine" :engine="engine" :items="items" />
>     <div ref="container" style="min-height: 500px"></div>
>   </div>
> </template>
> 
> <script>
> let Component = {
>   data: function () {
>     return {
>       engine: null,
>       items: []
>     };
>   },
> }
> if (!process.client) {
> } else {
>   console.log(process)
>   const Engine = require('@aomao/engine').default
>   const Heading = require('@aomao/plugin-heading').default
>   const AmToolbar = require('am-editor-toolbar-vue2')
>   const { ToolbarPlugin, ToolbarComponent } = AmToolbar
>   const CodeBlock = require('am-editor-codeblock-vue2')
>   const { CodeBlockComponent } = CodeBlock
>   const Bold = require('@aomao/plugin-bold').default
>   const Alignment = require('@aomao/plugin-alignment').default
>   const BackColor = require('@aomao/plugin-backcolor').default
>   const Code = require('@aomao/plugin-code').default
>   const File = require('@aomao/plugin-file').default
>   const FontColor = require('@aomao/plugin-fontcolor').default
>   const FontSize = require('@aomao/plugin-fontsize').default
>   const FontFamily = require('@aomao/plugin-fontfamily').default
>   const Hr = require('@aomao/plugin-hr').default
>   const Indent = require('@aomao/plugin-indent').default
>   const Italic = require('@aomao/plugin-italic').default
>   const Image = require('@aomao/plugin-image')
>   const { ImageComponent } = Image
>   const Link = require('@aomao/plugin-link').default
>   const LineHeight = require('@aomao/plugin-line-height').default
>   // const LightBlock = require('@aomao/plugin-lightblock') // 插件无法安装
>   const Mark = require('@aomao/plugin-mark').default
>   const MarkRange = require('@aomao/plugin-mark-range').default
>   const Math = require('@aomao/plugin-math').default
>   const Mention = require('@aomao/plugin-mention').default
>   const OrderedList = require('@aomao/plugin-orderedlist').default
>   const PaintFormat = require('@aomao/plugin-paintformat').default
>   const Quote = require('@aomao/plugin-quote').default
>   const Redo = require('@aomao/plugin-redo').default
>   const RemoveFormat = require('@aomao/plugin-removeformat').default
>   const SelectAll = require('@aomao/plugin-selectall').default
>   const StrikeThrough = require('@aomao/plugin-strikethrough').default
>   const Status = require('@aomao/plugin-status').default
>   const Sub = require('@aomao/plugin-sub').default
>   const Sup = require('@aomao/plugin-sup').default
>   const Table = require('@aomao/plugin-table')
>   const { TableComponent } = Table
>   const TaskList = require('@aomao/plugin-tasklist').default
>   const Underline = require('@aomao/plugin-underline').default
>   const Undo = require('@aomao/plugin-undo').default
>   const UnorderedList = require('@aomao/plugin-unorderedlist').default
>   const Video = require('@aomao/plugin-video').default
> 
>   Component = {
>     name: "HelloWorld",
>     components: {
>       AmToolbar: AmToolbar.default,
>     },
>     data: function () {
>       return {
>         engine: null,
>         items: [['collapse'],['heading','bold']]
>       };
>     },
>     props: {
>       msg: String,
>     },
>     mounted() {
>       this.engine = new Engine(
>         this.$refs.container,
>         {
>           config:{
>             "heading":{
>               //修改快捷键
>               hotkey:{
>                 h1:"快捷键"
>               }
>             }
>           },
>           cards: [
>             ToolbarComponent,
>             CodeBlockComponent,
>             ImageComponent,
>             TableComponent
>           ],
>           plugins: [
>             Heading,
>             ToolbarPlugin,
>             CodeBlock.default,
>             Bold,
>             Alignment,
>             BackColor,
>             Code,
>             File,
>             FontColor,
>             FontSize,
>             FontFamily,
>             Hr,
>             Indent,
>             Italic,
>             Image.default,
>             Link,
>             LineHeight,
>             Mark,
>             MarkRange,
>             Math,
>             Mention,
>             OrderedList,
>             PaintFormat,
>             Quote,
>             Redo,
>             RemoveFormat,
>             SelectAll,
>             StrikeThrough,
>             Status,
>             Sub,
>             Sup,
>             Table.default,
>             TaskList,
>             Underline,
>             Undo,
>             UnorderedList,
>             Video
>           ]
>         },
>       );
>     }
>   };
> }
> export default Component
> </script>
> 
> 
> <style scoped>
> h3 {
>   margin: 40px 0 0;
> }
> ul {
>   list-style-type: none;
>   padding: 0;
> }
> li {
>   display: inline-block;
>   margin: 0 10px;
> }
> a {
>   color: #42b983;
> }
> </style>
> ```

每当输入内容时，控制台都会报错

![image](https://user-images.githubusercontent.com/31246220/185306151-f3e3f4ae-e956-4a65-8837-41880bbbb3f6.png)

**Comment by big-camel** [comment]
mark-range 没有配置 keys https://editor.aomao.com/zh-CN/plugin/plugin-mark-range#%E6%A0%87%E8%AE%B0%E7%B1%BB%E5%9E%8B%E9%9B%86%E5%90%88

**Comment by know-that** [comment]
> mark-range 没有配置 keys https://editor.aomao.com/zh-CN/plugin/plugin-mark-range#%E6%A0%87%E8%AE%B0%E7%B1%BB%E5%9E%8B%E9%9B%86%E5%90%88

@aomao/plugin-lightblock 这个插件装不上可以再帮忙看看吗

**Comment by big-camel** [comment]
> > mark-range 没有配置 keys https://editor.aomao.com/zh-CN/plugin/plugin-mark-range#%E6%A0%87%E8%AE%B0%E7%B1%BB%E5%9E%8B%E9%9B%86%E5%90%88
> 
> @aomao/plugin-lightblock 这个插件装不上可以再帮忙看看吗

因为他只能用于 react

**Comment by know-that** [comment]
> > > mark-range 没有配置 keys https://editor.aomao.com/zh-CN/plugin/plugin-mark-range#%E6%A0%87%E8%AE%B0%E7%B1%BB%E5%9E%8B%E9%9B%86%E5%90%88
> > 
> > 
> > @aomao/plugin-lightblock 这个插件装不上可以再帮忙看看吗
> 
> 因为他只能用于 react

好的，没看到文档上括号
