### ISSUE TITLE
markdown 图片语法进行空格转换的时候转为 codeblock 了

### ISSUE THREAD

**Issue by know-that** [yanmao-cc/am-editor-nuxt#4]
如题，官网也是这样，nuxt版本也是
<img width="1101" alt="image" src="https://user-images.githubusercontent.com/31246220/185750512-daa7eb8f-865f-44f1-b044-8c8767273de6.png">
<img width="1196" alt="image" src="https://user-images.githubusercontent.com/31246220/185750523-aa82fedd-e0b3-4008-836e-fd770e2bb6a9.png">

另外，方便添加你微信或者QQ吗

**Comment by big-camel** [comment]
这个bug修好了，你可以加一下群 907664876
